---
- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: true

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
    daemon_reload: true
